import os
import random
import time
import gradio as gr
from gradio_client import Client, handle_file

MODEL_SPACE = "yisol/IDM-VTON"
MAX_SEED = 2147483647

_client = None


def get_client():
    global _client

    if _client is None:
        _client = Client(MODEL_SPACE)

    return _client


def get_garment_description(category):
    descriptions = {
        "Upper Body": "upper body garment, shirt, t-shirt, top, blouse or jacket",
        "Lower Body": "lower body garment, pants, trousers or skirt",
        "Dress": "full body dress or one-piece outfit"
    }

    return descriptions.get(
        category,
        "clothing garment"
    )


def run_virtual_tryon(
    person_image,
    garment_image,
    garment_category,
    seed,
    randomize_seed,
    denoise_steps,
    auto_crop,
    progress=gr.Progress()
):
    if person_image is None:
        return None, "Please upload a person image."

    if garment_image is None:
        return None, "Please upload a garment image."

    try:
        progress(
            0.05,
            desc="Connecting to AI virtual try-on model..."
        )

        client = get_client()

        if randomize_seed:
            seed = random.randint(0, MAX_SEED)

        seed = int(seed)

        garment_description = get_garment_description(
            garment_category
        )

        progress(
            0.20,
            desc="Uploading person and garment..."
        )

        person_file = handle_file(person_image)
        garment_file = handle_file(garment_image)

        progress(
            0.35,
            desc="Analyzing person and garment..."
        )

        progress(
            0.50,
            desc="Generating virtual try-on..."
        )

        result = client.predict(
            dict={
                "background": person_file,
                "layers": [],
                "composite": None
            },
            garm_img=garment_file,
            garment_des=garment_description,
            is_checked=True,
            is_checked_crop=auto_crop,
            denoise_steps=int(denoise_steps),
            seed=seed,
            api_name="/tryon"
        )

        progress(
            0.92,
            desc="Preparing final result..."
        )

        if result is None:
            return None, "The AI model did not return a result."

        output_image = None

        if isinstance(result, (list, tuple)):
            for item in result:
                if item is not None:
                    output_image = item
                    break
        else:
            output_image = result

        if output_image is None:
            return None, "No output image was returned by the VTON model."

        progress(
            1.0,
            desc="Virtual try-on completed!"
        )

        elapsed_message = (
            "Virtual Try-On Complete\n\n"
            f"Model: IDM-VTON\n"
            f"Garment: {garment_category}\n"
            f"Seed: {seed}\n"
            f"Denoising steps: {denoise_steps}\n\n"
            "The result was generated by the VTON model."
        )

        return output_image, elapsed_message

    except Exception as error:
        error_text = str(error)

        if "queue" in error_text.lower():
            message = (
                "The public AI model is currently busy.\n\n"
                "Please wait a little and try again."
            )

        elif "timeout" in error_text.lower():
            message = (
                "The AI model took too long to respond.\n\n"
                "Please try again."
            )

        elif "connection" in error_text.lower():
            message = (
                "Could not connect to the VTON model.\n\n"
                "The Hugging Face Space may temporarily be unavailable."
            )

        else:
            message = (
                "Virtual try-on failed.\n\n"
                f"Error: {error_text}"
            )

        return None, message


def reset_app():
    return (
        None,
        None,
        None,
        42,
        True,
        30,
        False,
        "Ready"
    )


CSS = """
body {
    background:
        radial-gradient(
            circle at 10% 0%,
            #24204f 0%,
            #090b18 38%,
            #05060c 100%
        ) !important;
}

.gradio-container {
    max-width: 1400px !important;
    margin: auto !important;
    background: transparent !important;
}

.hero {
    text-align: center;
    padding: 45px 20px 30px;
}

.hero-badge {
    display: inline-block;
    padding: 8px 16px;
    border-radius: 50px;
    background: rgba(139, 124, 255, 0.15);
    border: 1px solid rgba(139, 124, 255, 0.35);
    color: #c9c2ff;
    font-size: 13px;
    font-weight: 700;
    letter-spacing: 1px;
}

.hero h1 {
    font-size: clamp(40px, 6vw, 72px);
    line-height: 1;
    margin: 18px 0 12px;
    color: white;
    letter-spacing: -3px;
}

.hero p {
    max-width: 750px;
    margin: auto;
    color: #aeb5ca;
    font-size: 18px;
    line-height: 1.7;
}

.card {
    border: 1px solid rgba(255,255,255,0.09) !important;
    border-radius: 24px !important;
    background: rgba(18, 22, 40, 0.75) !important;
    box-shadow: 0 25px 80px rgba(0,0,0,0.25);
    padding: 10px !important;
}

.section-title {
    color: #ffffff;
    font-weight: 700;
    font-size: 18px;
}

.info-box {
    border: 1px solid rgba(255,255,255,0.08);
    background: rgba(255,255,255,0.035);
    border-radius: 18px;
    padding: 20px;
    color: #b8bfd2;
    line-height: 1.7;
}

.pipeline {
    text-align: center;
    padding: 25px 10px;
    color: #aeb5ca;
}

.pipeline strong {
    color: #ffffff;
}

.footer {
    text-align: center;
    padding: 35px 10px 10px;
    color: #717a95;
    font-size: 13px;
}
"""


with gr.Blocks(
    title="AI Fashion Fitting",
    css=CSS,
    theme=gr.themes.Soft(
        primary_hue="violet",
        neutral_hue="slate"
    )
) as app:

    gr.HTML(
        """
        <div class="hero">

            <div class="hero-badge">
                COMPUTER VISION · GENERATIVE AI
            </div>

            <h1>
                AI Fashion Fitting
            </h1>

            <p>
                Upload a person and a garment.
                Generate an AI-powered virtual try-on result
                using a high-fidelity virtual try-on model.
            </p>

        </div>
        """
    )

    with gr.Row():

        with gr.Column(
            scale=1,
            elem_classes="card"
        ):

            gr.Markdown(
                "### 01 · Upload Person",
                elem_classes="section-title"
            )

            person_image = gr.Image(
                label="Person Photo",
                sources=[
                    "upload",
                    "webcam"
                ],
                type="filepath",
                height=450
            )

            gr.Markdown(
                """
                **Recommended:** clear photo with one visible person.
                """
            )

        with gr.Column(
            scale=1,
            elem_classes="card"
        ):

            gr.Markdown(
                "### 02 · Upload Garment",
                elem_classes="section-title"
            )

            garment_image = gr.Image(
                label="Garment / Outfit",
                sources=["upload"],
                type="filepath",
                height=450
            )

            gr.Markdown(
                """
                **Recommended:** clear garment image with good lighting.
                """
            )

        with gr.Column(
            scale=1,
            elem_classes="card"
        ):

            gr.Markdown(
                "### 03 · Result",
                elem_classes="section-title"
            )

            result_image = gr.Image(
                label="AI Virtual Try-On",
                type="filepath",
                height=450
            )

            gr.Markdown(
                """
                The result is generated by the connected VTON model.
                """
            )

    gr.Markdown("## Generation Settings")

    with gr.Row():

        garment_category = gr.Dropdown(
            choices=[
                "Upper Body",
                "Lower Body",
                "Dress"
            ],
            value="Upper Body",
            label="Garment Category"
        )

        denoise_steps = gr.Slider(
            minimum=20,
            maximum=40,
            value=30,
            step=1,
            label="Denoising Steps"
        )

        seed = gr.Number(
            value=42,
            minimum=0,
            maximum=MAX_SEED,
            precision=0,
            label="Seed"
        )

        randomize_seed = gr.Checkbox(
            value=True,
            label="Random Seed"
        )

        auto_crop = gr.Checkbox(
            value=False,
            label="Auto Crop"
        )

    with gr.Row():

        generate_button = gr.Button(
            "✨ Generate Virtual Try-On",
            variant="primary",
            size="lg"
        )

        reset_button = gr.Button(
            "Reset",
            size="lg"
        )

    status = gr.Textbox(
        label="Generation Status",
        value="Ready",
        lines=8,
        interactive=False
    )

    gr.HTML(
        """
        <div class="pipeline">

            <strong>Person Image</strong>
            &nbsp; → &nbsp;

            <strong>Pose & Human Parsing</strong>
            &nbsp; → &nbsp;

            <strong>Garment Conditioning</strong>
            &nbsp; → &nbsp;

            <strong>Generative VTON</strong>
            &nbsp; → &nbsp;

            <strong>Final Result</strong>

        </div>
        """
    )

    with gr.Row():

        with gr.Column(elem_classes="card"):

            gr.Markdown(
                """
                ### How it works

                This application sends the uploaded person and garment
                to a genuine virtual try-on model rather than simply
                placing one image over another.

                The underlying IDM-VTON Space performs human parsing,
                pose processing, garment conditioning and generative
                image synthesis.
                """
            )

        with gr.Column(elem_classes="card"):

            gr.Markdown(
                """
                ### Better input = better result

                • Use one clearly visible person  
                • Prefer good lighting  
                • Keep the person's body reasonably visible  
                • Use a clear garment/product image  
                • Choose the correct garment category  
                • Try another seed if the first result is poor
                """
            )

    gr.HTML(
        """
        <div class="footer">
            AI Fashion Fitting · Advanced Computer Vision Prototype
        </div>
        """
    )

    generate_button.click(
        fn=run_virtual_tryon,
        inputs=[
            person_image,
            garment_image,
            garment_category,
            seed,
            randomize_seed,
            denoise_steps,
            auto_crop
        ],
        outputs=[
            result_image,
            status
        ],
        api_name="generate_tryon",
        concurrency_limit=1
    )

    reset_button.click(
        fn=reset_app,
        inputs=[],
        outputs=[
            person_image,
            garment_image,
            result_image,
            seed,
            randomize_seed,
            denoise_steps,
            auto_crop,
            status
        ]
    )


if __name__ == "__main__":

    print("=" * 60)
    print("AI Fashion Fitting")
    print("Connecting to IDM-VTON through Gradio Client")
    print("=" * 60)

    app.queue(
        default_concurrency_limit=1
    ).launch(
        server_name="127.0.0.1",
        server_port=int(os.getenv("PORT", "7860")),
        share=False
    )